export const FETCH_POSTS = 'FETCH_POSTS'
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS'
export const FETCH_POSTS_FAILURE = 'FETCH_POSTS_FAILURE'

export const GET_POST='GET_POST'
export const GET_POST_SUCCESS='GET_POST_SUCCESS'
export const GET_POST_FAILURE='GET_POST_FAILURE'

export const ADD_POST = 'ADD_POST'
export const POST_VOTE = 'POST_VOTE'
export const ADD_COMMENT = 'ADD_COMMENT'
export const COMMENT_VOTE = 'COMMENT_VOTE'
export const SELECT_POST = 'FETCH_COMMENTS'
export const VOTE_REQUEST = 'VOTE_REQUEST'
export const ADD_REQUEST = 'ADD_REQUEST'
export const ADD_POSTS = 'ADD_POSTS'
export const GET_USER = 'GET_USER'
export const GET_MAP_FEATURES = 'GET_MAP_FEATURES'

export const AUTH_REQUEST = 'AUTH_REQUEST'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_ERROR = 'AUTH_ERROR'

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_ERROR = 'SIGNUP_ERROR'
export const SET_IMAGE = 'SET_IMAGE'

export const FETCH_SAVED_POST = 'FETCH_SAVED_POST'
export const FETCH_SAVED_POST_SUCCESS = 'FETCH_SAVED_POST_SUCCESS'
export const FETCH_SAVED_POST_FAILURE = 'FETCH_SAVED_POST_FAILURE'

export const FETCH_MY_POSTS = 'FETCH_MY_POSTS'
export const FETCH_MY_POSTS_SUCCESS = 'FETCH_MY_POSTS_SUCCESS'
export const FETCH_MY_POSTS_ERROR = 'FETCH_MY_POSTS_ERROR'

export const FETCH_KARMA = 'FETCH_KARMA'
